### ISSUE TITLE
IV-SDK .NET scripts can work on Linux

### ISSUE THREAD

**Issue by Nelson340** [gillian-guide/gillian-guide.github.io#11]
https://gillian-guide.github.io/mod-dependencies/

This page says IV-SDK .NET is "Not compatible with Linux", but I've been able to use it on Linux via running GTAIV in Bottles rather than Steam. What I did was:

1. Set my Bottle's OS to Windows 7
2. Install .NET framework 4.8 on the Bottle
3. Set the OS back to 10

Using Protontricks, it's also possible to do something similar with the Proton prefix Steam makes for IV.

**Comment by SandeMC** [comment]
I'm aware of these really hacky setups, but I need some consistent and easy to follow guide to actually incorporate it into the guide
