### ISSUE TITLE
A few issues with other mods

### ISSUE THREAD

**Issue by mateus3c** [gillian-guide/gillian-guide.github.io#17]
I installed the drag and drop archive and everything works fine, but when I tried to install other mods mentioned on [https://gillian-guide.github.io/extras/mods/](https://gillian-guide.github.io/extras/mods/) I faced a few issues.

So, the mods I tried to install were [Project Birds](https://gtaforums.com/topic/980018-project-birds) and [Liberty Rush](https://gtaforums.com/topic/979688-liberty-rush/). First of all I want to mention that I checked 5 times if I had done the installation for both mods correctly (following the mod compatibility .txt file inside their respective downloads). I also started a new save file every time I made my tests. My commandline is the one you recommended for when playing with dxvk (I used your GTAIVSetupUtilityWPF to install dxkv and setup launch options)

> -norestrictions
> -nomemrestrict
> -windowed
> -availablevidmem 3072.0

Here's my tests results:
**Drag and Drop Archive + Project Birds:** Missing textures and invisible stuff.
Details: After the cutscene ends Niko falls in the water while inside the car.
![image](https://github.com/user-attachments/assets/bd8b1e9a-c370-4c84-8471-7a7e7ca68c33)
![image](https://github.com/user-attachments/assets/e81e33ed-aed6-4d25-a01c-23cc9df483c0)

**Drag and Drop Archive + Liberty Rush:** Infinite loading screen.
Details: After the loading screen with the game characters arts for a brief moment Niko appears T Posing on the air while the map loads, then the screen turns black and it infinite loads the first game mission.
![image](https://github.com/user-attachments/assets/699bcfed-c0c2-45d5-a928-f86abc2193b9)

**Drag and Drop Archive + Project Birds + Liberty Rush:** Infinite loading screen and missing textures
Details: After the loading screen with the game characters arts for a brief moment Niko appears T Posing on the air, *then he falls on the water while the map loads*, then the screen turns black and it infinite loads the first game mission.
![image](https://github.com/user-attachments/assets/7b4957c6-bbe6-4964-b3f7-f1d7abf2bf02)

> My PC specs are:
> I7-10750H
> GTX 1660ti (4gb)
> 32Gb RAM

I have the steam version of the game and yeah, I think that's all the details I could possible give lol

**Comment by mateus3c** [comment]
I'm 5 days trying to get this to work lol

**Comment by SandeMC** [comment]
First of all, are you using the update folder?

Second of all, are you not corrupting your original files? It looks like you're somehow erasing whole files out of existence instead of properly adding to vanilla files, please read the modloading page better

And to end it off and to close the issue, I don't support any modifications that aren't "additional mods" to the archive, for the exact same reasons you have issues - my archive is either incompatible, or you are failing to install mods correctly.
