### ISSUE TITLE
Mining software?

### ISSUE THREAD

**Issue by LexiAMustela** [gillian-guide/gillian-guide.github.io#18]
When I was downgrading with your utility, a file called "Vigua.A" showed up on Windows Defender, which said it came from Ultimate ASI Loader. But when I looked up the file's name, people said it was mining software?

**Comment by SandeMC** [comment]
False positive, my tool downloads from the official upload https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases
which TAG refuses to request to de-mark as false positive

it should get detected as a PUA though not as whatever you got, might want to check your system with an AV?

**Comment by LexiAMustela** [comment]
It did get detected as a PUA, but I was unsure if it was safe.

**Comment by SandeMC** [comment]
Report here if it bothers you, I'm blocked by TAG
https://github.com/ThirteenAG/Ultimate-ASI-Loader/issues

Attach this to report a false positive, too: https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper
