### ISSUE TITLE
Less mod lists from the enhacement tab

### ISSUE THREAD

**Issue by ghost** [gillian-guide/gillian-guide.github.io#23]
I think you should have added more mods to the enhancement tab, so I will suggest few mods that you check out (of course you decide what to add and what to keep). Before you start judging, please read the info below the mod's name and test it.

1. Vanilla-Friendly HD Roads: https://www.gtainside.com/en/gta4/mods/186727-vanilla-friendly-hd-roads/
This a very very vanilla-friendly mod that upscales the roads of Liberty City into high resolution while very carefully preserve the original look (you need to set your Texture Filter Quality to Anisotropic 16x for the best result)

2. Biker Extreme (EFLC only, but only recommended for TLAD): https://gtaforums.com/topic/978897-biker-extreme/ 
This mod gives Johnny and Luis the ability to use their Exclusive Shotguns while on bike, keep in mind that I only recommend the TLAD version for The Lost and Damned, becuase for TLAD, it restores a beta feature and it looks authentic and vanilla friendly while in TBoGT it is out of place. So only use it in TLAD.

3. Underwater and Diving Mechanics: https://zolika1351.pages.dev/mods/ivdiving
This is a great mod that adds an entire underwater world (kind of WIP) plus swimming mechanics from GTA San Andreas, it is great because this feature is been requested since 16 years and Zolika1351 added it in the most faithful way possible.

4. Perfect Ocean IV: https://www.gtainside.com/en/gta4/mods/97955-perfect-ocean-iv
This mod is great becuase it upscales the water into 4k and it makes it so natural yet so faithful that it doesn't break the game's atmosphere.

5. Whiz Wireless Phone: https://www.gtainside.com/en/gta4/mods/171211-whiz-wireless-phone
This mod ports the phone model from cutscenes into the gameplay, with proper collision and it supports all phone themes.

6. New Outlook Trees: Go to Attramet's workshop and open the Workshop Releases tab and it should be under "Beta Clothes Textures"
This is a great mod that ports beta outlook park trees to PC, you need Console Visuals though as the mod was using console trees.

7. Beta Props: keep scrolling in the same Workshop Releases tab until you see that's under Fixed Car Wash price text.
This mod changes the props appearance to be more like beta ones, it looks even better with FusionFix or ZolikaPatch

That's all the mods that I highly recommend, please don't get me worng or judge me before you test these mods or at least read more about them in the mod pages. I hope you doing well

**Comment by SandeMC** [comment]
I believe I answered these on the server already, but all of those got denied for reasons, sorry.

**Comment by ghost** [comment]
Don't worry about it, it's fine. Maybe you're right though, these mods got denied for logical reasons.

By the way can you update your guide a little fixing some mistakes (like wrong links) maybe adding new information etc.
