### ISSUE TITLE
Just wanted to say thanks.

### ISSUE THREAD

**Issue by EftzL06** [gillian-guide/gillian-guide.github.io#26]
So Saturday i decided to give GFWL a try. Thing had always been hit or miss, but thanks to your downgrader and FF GFLW patch i could play it with no issues at all, and with the amazing FusionFix and ZolikaPatch fixes. It really was a beatiful experience and i still get most SP fixes as well. From the bottom of my heart, thank you!

**Comment by SandeMC** [comment]
No problem
