### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by Lethality5001** [gillian-guide/gillian-guide.github.io#9]
Hi can u make fusionfix compatible with snowmod?

**Comment by SandeMC** [comment]
I don't make, port or edit any mods. If the snow mod doesn't have any scripts, see [this](https://gillian-guide.github.io/extras/openiv/) and [this page](https://gillian-guide.github.io/extras/modloading/) for setting it up yourself.

**Comment by SandeMC** [comment]
However,

**Comment by SandeMC** [comment]
However, I repacked the mod now.
